git add ".env.example"
git commit -m "Update environment example configuration"
git add "README.md"
git commit -m "Refresh project README documentation"
git add "backend/Dockerfile"
git commit -m "Update backend container build configuration"
git add "backend/config.py"
git commit -m "Refine backend configuration settings"
git add "backend/ingestion/log_parser.py"
git commit -m "Update ingestion log parsing behavior"
git add "backend/ingestion/normalizer.py"
git commit -m "Adjust ingestion normalization logic"
git add "backend/main.py"
git commit -m "Update backend application entrypoint"
git add "backend/models.py"
git commit -m "Revise backend data models"
git add "backend/nlq/query_engine.py"
git commit -m "Update natural language query engine"
git add "backend/rag/indexer.py"
git commit -m "Refine RAG indexing workflow"
git add "backend/rag/pipeline.py"
git commit -m "Update RAG pipeline orchestration"
git add "backend/rag/retriever.py"
git commit -m "Adjust RAG retrieval behavior"
git add "backend/schema.py"
git commit -m "Update backend schema definitions"
git add "docker-compose.yml"
git commit -m "Update local compose services"
git add "frontend/Dockerfile"
git commit -m "Update frontend container build configuration"
git add "frontend/nginx.conf"
git commit -m "Revise frontend nginx configuration"
git add "frontend/package.json"
git commit -m "Update frontend package metadata"
git add "frontend/src/api/raptorApi.js"
git commit -m "Update frontend RAPTOR API client"
git add "frontend/src/components/Dashboard.jsx"
git commit -m "Refresh dashboard component behavior"
git add "scripts/hybrid/install_linux.sh"
git commit -m "Update hybrid Linux installation script"
git add "tests/test_api_persistence_connectors.py"
git commit -m "Update API persistence connector tests"
git add "backend/requirements.lock"
git commit -m "Add backend dependency lockfile"
git add "docker-compose.prod.yml"
git commit -m "Add production compose configuration"
git add "docs/data-governance.md"
git commit -m "Add data governance documentation"
git add "docs/scaling-limits.md"
git commit -m "Add scaling limits documentation"
git add "docs/production-runbook.md"
git commit -m "Add production runbook documentation"
git add "docs/threat-model.md"
git commit -m "Add threat model documentation"
