import json
import re
from typing import List, Dict, Optional
from loguru import logger

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from config import REPORT_GENERATION_PROMPT
from schema import AnalysisResult, AttributionResult
from rag.pipeline import call_llm

REPORT_VERSION_MARKER = "<!-- RAPTOR_ENTERPRISE_REPORT_V2 -->"


def generate_report(
    analysis: AnalysisResult,
    attribution: List[AttributionResult],
    graph_summary: Dict,
    investigation_id: str = "",
    report_name: str = "",
) -> str:
    """
    Generate a full natural-language investigation report.
    """
    logger.info(f"Generating investigation report for {investigation_id}")

    # Format findings for prompt
    findings_data = []
    for f in analysis.findings:
        findings_data.append({
            "technique_id": f.technique_id,
            "technique_name": f.technique_name,
            "tactics": f.tactics,
            "kill_chain_phase": f.kill_chain_phase,
            "confidence": f.confidence,
            "evidence_summary": f.evidence_summary,
            "apt_indicators": f.apt_indicators,
        })

    # Format attribution for prompt
    attribution_data = []
    for a in attribution:
        attribution_data.append({
            "apt_name": a.apt_name,
            "confidence_score": f"{a.confidence_score:.0%}",
            "confidence_label": a.confidence_label,
            "overlapping_ttps": a.overlapping_ttps,
            "penalties": a.penalties_applied,
            "bonuses": a.bonuses_applied,
        })

    prompt = REPORT_GENERATION_PROMPT.format(
        findings_json=json.dumps(findings_data, indent=2),
        attribution_json=json.dumps(attribution_data, indent=2),
        graph_summary=json.dumps(graph_summary, indent=2),
    )

    system = """You are a senior incident response report writer for an enterprise SOC.
Write a board-ready but technical Markdown report. Do not paste raw JSON. Do not use
placeholder language. Include evidence-grounded findings, ATT&CK IDs, attribution
caveats, impact, and prioritized response actions."""

    try:
        report = _normalize_llm_report(
            call_llm(system, prompt),
            analysis,
            attribution,
            graph_summary,
            investigation_id,
            report_name,
        )
    except Exception as e:
        logger.error(f"Report LLM failed, using deterministic report: {e}")
        report = build_enterprise_report(
            analysis,
            attribution,
            graph_summary,
            investigation_id,
            report_name=report_name,
            generation_note=f"Deterministic report engine used after LLM report step failed: {str(e)[:180]}",
        )
    logger.info(f"Report generated ({len(report)} chars)")
    return report


def report_needs_upgrade(report: str) -> bool:
    """Return True when a stored report is missing or still in the old raw format."""
    value = str(report or "").strip()
    if not value:
        return True
    if REPORT_VERSION_MARKER in value:
        return False
    legacy_markers = (
        "# RAPTOR Investigation Report",
        "_Generated by deterministic fallback",
        "LLM/RAG fallback used:",
        "## Graph Summary",
    )
    return any(marker in value for marker in legacy_markers)


def build_enterprise_report(
    analysis: AnalysisResult,
    attribution: List[AttributionResult],
    graph_summary: Dict,
    investigation_id: str = "",
    report_name: str = "",
    generation_note: str = "",
) -> str:
    top = attribution[0] if attribution else None
    findings = analysis.findings or []
    risk = _risk_label(findings)
    hosts = _unique_extracted("host", findings)
    users = _unique_extracted("user", findings)
    processes = _unique_extracted("process", findings)
    attack_sequence = analysis.attack_sequence or [f.technique_id for f in findings if f.technique_id]
    attack_sequence = _dedupe(attack_sequence)

    lines = [
        REPORT_VERSION_MARKER,
        "# Enterprise Forensic Investigation Report",
        "",
        f"**Case:** {report_name or investigation_id or 'Unnamed investigation'}",
        f"**Investigation ID:** `{investigation_id or 'unknown'}`",
        f"**Report State:** Finalized and stored with the investigation record",
        "",
        "## Executive Summary",
    ]

    if top:
        lines.extend([
            (
                f"RAPTOR reviewed {graph_summary.get('total_events', 0)} event(s) and validated "
                f"{len(findings)} ATT&CK technique finding(s). The strongest attribution candidate "
                f"is **{top.apt_name or 'Unknown'}** at {top.confidence_score:.0%} confidence "
                f"({top.confidence_label})."
            ),
            (
                f"The case is assessed as **{risk}** risk based on observed technique confidence, "
                f"affected hosts, credential exposure indicators, and lateral movement evidence."
            ),
            "Attribution remains an intelligence lead, not proof of actor identity; it should be corroborated with infrastructure, malware, victimology, and external reporting.",
        ])
    else:
        lines.extend([
            (
                f"RAPTOR reviewed {graph_summary.get('total_events', 0)} event(s) and validated "
                f"{len(findings)} ATT&CK technique finding(s)."
            ),
            "Attribution evidence was insufficient for a high-confidence actor assessment.",
        ])

    lines.extend([
        "",
        "## Scope And Key Indicators",
        "",
        "| Indicator | Value |",
        "| --- | --- |",
        f"| Events Reviewed | {graph_summary.get('total_events', 0)} |",
        f"| Unique Hosts | {graph_summary.get('unique_hosts', 0)} |",
        f"| Compromised / Lateral Hosts | {graph_summary.get('hosts_compromised', 0)} |",
        f"| Campaign Duration | {graph_summary.get('campaign_duration_hours', 0):.1f} hours |",
        f"| Affected Hosts | {', '.join(hosts) if hosts else 'Not extracted from evidence summaries'} |",
        f"| Observed Users | {', '.join(users) if users else 'Not extracted from evidence summaries'} |",
        f"| Observed Processes | {', '.join(processes[:8]) if processes else 'Not extracted from evidence summaries'} |",
        "",
        "## Attack Narrative",
        "",
        _attack_narrative(findings, attack_sequence),
        "",
        "## Validated ATT&CK Findings",
        "",
    ])

    if findings:
        lines.extend([
            "| ATT&CK ID | Technique | Tactic | Confidence | Evidence Statement |",
            "| --- | --- | --- | --- | --- |",
        ])
        for finding in findings:
            lines.append(
                "| "
                f"`{finding.technique_id}` | "
                f"{_clean_cell(finding.technique_name or finding.technique_id)} | "
                f"{_clean_cell(_format_phase(finding.kill_chain_phase or ', '.join(finding.tactics or [])))} | "
                f"{_clean_cell(finding.confidence or 'unknown')} | "
                f"{_clean_cell(_evidence_statement(finding))} |"
            )
    else:
        lines.append("No ATT&CK techniques were identified by the analysis pipeline.")

    lines.extend([
        "",
        "## Attack Sequence",
        "",
        " -> ".join(f"`{tid}`" for tid in attack_sequence) if attack_sequence else "No ordered technique sequence was available.",
        "",
        "## Attribution Assessment",
        "",
    ])
    if attribution:
        lines.extend([
            "| Candidate | Confidence | Label | Overlapping TTPs | Adjustments |",
            "| --- | --- | --- | --- | --- |",
        ])
        for result in attribution:
            lines.append(
                "| "
                f"{_clean_cell(result.apt_name or 'Unknown')} | "
                f"{result.confidence_score:.0%} | "
                f"{_clean_cell(result.confidence_label or 'UNKNOWN')} | "
                f"{_clean_cell(', '.join(result.overlapping_ttps[:12]) or 'None')} | "
                f"{_clean_cell('; '.join([*result.penalties_applied, *result.bonuses_applied]) or 'None')} |"
            )
    else:
        lines.append("No attribution candidate data was available.")

    lines.extend([
        "",
        "## Containment And Response Priorities",
        "",
        "1. Isolate affected hosts while preserving volatile forensic evidence and endpoint telemetry.",
        "2. Reset credentials associated with observed users, privileged sessions, and affected systems.",
        "3. Hunt for the validated ATT&CK techniques across adjacent hosts, authentication logs, process telemetry, and egress records.",
        "4. Review and block remote administration, C2, and lateral movement paths observed during the campaign window.",
        "5. Preserve raw evidence, investigation graph output, and audit trail before destructive containment actions.",
        "",
        "## Evidence Appendix",
        "",
    ])

    if findings:
        lines.extend([
            "| Technique | Event References | Source Note |",
            "| --- | --- | --- |",
        ])
        for finding in findings:
            event_refs = ", ".join(_short_id(eid) for eid in finding.event_ids[:12]) or "None reported"
            lines.append(
                "| "
                f"`{finding.technique_id}` { _clean_cell(finding.technique_name or '') } | "
                f"{_clean_cell(event_refs)} | "
                f"{_clean_cell(_source_note(finding))} |"
            )
    else:
        lines.append("No evidence appendix entries were available.")

    lines.extend([
        "",
        "## Analyst Handling Notes",
        "",
        "- This report is generated from structured RAPTOR investigation output and persisted with the case record.",
        "- Review raw telemetry and case notes before external distribution.",
        "- Re-run the investigation only when source evidence or detection logic changes.",
    ])
    if generation_note:
        lines.append(f"<!-- {generation_note} -->")
    return "\n".join(lines)


def _normalize_llm_report(
    raw_report: str,
    analysis: AnalysisResult,
    attribution: List[AttributionResult],
    graph_summary: Dict,
    investigation_id: str,
    report_name: str = "",
) -> str:
    report = str(raw_report or "").strip()
    report = re.sub(r"^```(?:markdown|md)?\s*|\s*```$", "", report, flags=re.IGNORECASE | re.DOTALL).strip()
    if len(report) < 600 or "```json" in report.lower() or report.count("{") > 8:
        return build_enterprise_report(
            analysis,
            attribution,
            graph_summary,
            investigation_id,
            report_name=report_name,
            generation_note="LLM report output was normalized by deterministic enterprise report engine.",
        )
    if REPORT_VERSION_MARKER not in report:
        report = f"{REPORT_VERSION_MARKER}\n{report}"
    if not report.lstrip().startswith(REPORT_VERSION_MARKER):
        report = f"{REPORT_VERSION_MARKER}\n{report}"
    return report


def _risk_label(findings: List) -> str:
    levels = {str(f.confidence or "").lower() for f in findings}
    if "critical" in levels or "high" in levels:
        return "High"
    if "medium" in levels:
        return "Medium"
    return "Low" if findings else "Informational"


def _attack_narrative(findings: List, attack_sequence: List[str]) -> str:
    if not findings and not attack_sequence:
        return "No attack sequence could be reconstructed from the available evidence."
    first = findings[0] if findings else None
    last = findings[-1] if findings else None
    sequence_text = ", ".join(attack_sequence[:12]) if attack_sequence else "the validated findings"
    if first and last and first != last:
        return (
            f"The reconstructed activity begins with {first.technique_id} "
            f"({_clean_text(first.technique_name)}) and progresses through {sequence_text}. "
            f"The latest validated activity includes {last.technique_id} "
            f"({_clean_text(last.technique_name)}), indicating a multi-stage intrusion path."
        )
    if first:
        return f"The reconstructed activity centers on {first.technique_id} ({_clean_text(first.technique_name)}) with supporting telemetry in the case evidence."
    return f"The reconstructed activity follows these ATT&CK techniques: {sequence_text}."


def _evidence_statement(finding) -> str:
    summary = _clean_text(finding.evidence_summary)
    if summary:
        return summary
    return "Structured finding returned without an evidence narrative; review raw event IDs and source telemetry."


def _source_note(finding) -> str:
    summary = _clean_text(finding.evidence_summary)
    return summary[:220] if summary else "Review source telemetry for the associated event IDs."


def _format_phase(value: str) -> str:
    value = str(value or "unknown").replace("_", " ").replace("-", " ")
    return " ".join(part.capitalize() for part in value.split()) or "Unknown"


def _clean_text(value: str) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def _clean_cell(value: str) -> str:
    return _clean_text(value).replace("|", "\\|")


def _short_id(value: str) -> str:
    return str(value or "")[:12]


def _dedupe(values: List[str]) -> List[str]:
    seen = set()
    output = []
    for value in values:
        key = str(value or "").strip()
        if key and key not in seen:
            seen.add(key)
            output.append(key)
    return output


def _unique_extracted(field: str, findings: List) -> List[str]:
    values: list[str] = []
    pattern = re.compile(rf'"{re.escape(field)}"\s*:\s*"([^"]+)"')
    for finding in findings:
        summary = str(getattr(finding, "evidence_summary", "") or "")
        values.extend(match.group(1) for match in pattern.finditer(summary))
    return _dedupe(values)
